# Generated by Django 5.0 on 2023-12-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_police_dependence_remove_police_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepasswords',
            old_name='CODE',
            new_name='code',
        ),
    ]
