# Generated by Django 5.0 on 2023-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuarios_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepasswords',
            name='expiration',
            field=models.DateTimeField(default=None),
        ),
    ]
