# Generated by Django 5.0 on 2023-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_onetimepasswords_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepasswords',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
