# Generated by Django 5.0 on 2023-12-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usuarios_genre_alter_usuarios_type_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='type_dni',
            new_name='document_type',
        ),
    ]
