# Generated by Django 5.0 on 2024-01-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_dni_usuarios_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password_reset_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
