# Generated by Django 5.0 on 2024-01-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usuarios_password_reset_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password_reset_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
