# Generated by Django 5.0 on 2024-01-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usuarios_password_reset_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_reset_attempt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 6, 19, 22, 50, 206225, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
