# Generated by Django 5.0 on 2024-01-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usuarios_last_reset_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='last_reset_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
