# Generated by Django 5.0 on 2024-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_usuarios_last_reset_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('citizen', 'Ciudadano'), ('police', 'Policía'), ('administrator', 'Administrador')], default='citizen', max_length=15),
        ),
    ]
