# Generated by Django 5.0 on 2024-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_usuarios_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='phone_area_code',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='address',
            field=models.CharField(default='Alem', max_length=60),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='phone',
            field=models.CharField(default='468686', max_length=16),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('citizen', 'Ciudadano'), ('police', 'Policía'), ('administrator', 'Administrador')], max_length=15),
        ),
    ]
