# Generated by Django 5.0 on 2024-01-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_usuarios_address_number_usuarios_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='address_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='phone_area_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
