# Generated by Django 5.0 on 2024-02-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_usuarios_phone_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('citizen', 'Ciudadano'), ('police', 'Policía'), ('admin', 'Administrador')], max_length=15),
        ),
    ]
