# Generated by Django 5.0 on 2024-02-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_adress_dependence_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='hierarchy',
            field=models.CharField(blank=True, choices=[('ayudante', 'Ayudante'), ('subinspector', 'Subinspector'), ('inspector', 'Inspector'), ('agente', 'Agente'), ('cabo', 'Cabo'), ('cabo primero', 'Cabo Primero'), ('sargento', 'Sargento'), ('sargento primero', 'Sargento Primero')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('en curso', 'En curso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], max_length=10)),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tramite')),
                ('usuario_administrador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
