# Generated by Django 5.0 on 2024-02-10 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_payment_usuario_alter_usuarios_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cases',
            name='usuario_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativo', to=settings.AUTH_USER_MODEL),
        ),
    ]
