# Generated by Django 5.0 on 2024-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_cases_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='dni_dorso',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='cases',
            name='dni_frente',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
