# Generated by Django 5.0 on 2024-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_cases_dni_dorso_cases_dni_frente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='dni_dorso',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='dni_frente',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
