# Generated by Django 5.0 on 2024-02-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cases_dni_dorso_alter_cases_dni_frente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='dni_dorso',
            field=models.FileField(default='default_dni_dorso.jpg', upload_to='documents/'),
        ),
    ]
