# Generated by Django 5.0 on 2024-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_cases_dni_dorso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='dni_dorso',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='dni_frente',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
