# Generated by Django 5.0 on 2024-02-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_cases_dni_dorso_alter_cases_dni_frente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='dni_dorso',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='dni_frente',
        ),
    ]
