# Generated by Django 5.0 on 2024-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_cases_dni_dorso_cases_dni_frente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='entidad_solicitante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='madre_vive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='numero_hijos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='padre_vive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='dni_dorso',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='dni_frente',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
