# Generated by Django 5.0 on 2024-04-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_usuarios_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='certificado',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cases',
            name='comprobante_pago',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
