# Generated by Django 5.0.4 on 2024-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cases_certificado_cases_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='profile_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imagen/', verbose_name='Profile picture'),
        ),
    ]
