# Generated by Django 5.0 on 2024-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cases_certificado_cases_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('empleado', 'Empleado/a'), ('desocupado', 'Desocupado/a'), ('estudiante', 'Estudiante'), ('jubilado', 'Jubilado/a')], max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='residencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('en curso', 'En curso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado'), ('pendiente de pago', 'Pendiente de pago')], max_length=17),
        ),
    ]
