# Generated by Django 5.0.4 on 2024-06-09 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_usuarios_profile_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_Id', models.CharField(default='0', max_length=100, unique=True)),
                ('transaction_Amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('currency_Id', models.CharField(default='Unknown', max_length=10)),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('status_Detail', models.CharField(default='Unknown', max_length=100)),
                ('date_Approved', models.DateTimeField(default=django.utils.timezone.now)),
                ('paymentMethod_Id', models.CharField(default='Unknown', max_length=50)),
                ('cardholder_Name', models.CharField(default='Unknown', max_length=100)),
                ('last_Four_Digits', models.CharField(default='0000', max_length=4)),
                ('payer_Email', models.CharField(default='Unknown', max_length=50)),
                ('description', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
