# Generated by Django 5.0.4 on 2024-06-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_paymenttramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttramite',
            name='user_id',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
