# Generated by Django 5.0 on 2024-06-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_usuarios_profile_imagen'),
        ('api', '0039_cases_detalle_extravio'),
    ]

    operations = [
    ]
