# Generated by Django 5.0 on 2024-06-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20240603_1916'),
        ('api', '0040_paymenttramite_user_id'),
    ]

    operations = [
    ]
