# Generated by Django 5.0.4 on 2024-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_20240624_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='legajo_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
