# Generated by Django 5.0.4 on 2024-06-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_usuarios_legajo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dependence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
