# Generated by Django 5.0.4 on 2024-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_usuarios_dependence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('CDI', 'CDI'), ('CUIL', 'CUIL'), ('CUIT', 'CUIT')], max_length=9, null=True),
        ),
    ]
