# Generated by Django 5.0.4 on 2024-08-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_cases_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='observacion',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
