# Generated by Django 5.1 on 2024-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_usuarios_legajo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='comprobante_pago',
            field=models.FileField(null=True, upload_to='comprobantesPDF/'),
        ),
        migrations.AlterField(
            model_name='paymenttramite',
            name='transaction_Id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
