# Generated by Django 5.1 on 2024-08-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_rename_user_id_paymenttramite_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttramite',
            name='case_id',
            field=models.IntegerField(null=True),
        ),
    ]
